version: 2.1

jobs:
  build:
    docker: 
      - image: circleci/node:12.12.0
    steps:
      - checkout
      - run: 
          command: |
            npm install
            npx wdio run wdio.saucelabs.conf.js
