version: 2

jobs:
  execute_script:
    docker:
      - image: circleci/python:3.7.5
    steps:
      - checkout
      - run:
          name: execute simple Python script
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            python3 sandbox/json_builder.py

workflows:
  version: 2
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "40 * * * *"
          filters:
            branches:
              only:
                - master

    jobs:
      - execute_script