version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.5
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
         name: execute simple Python script
         command: |
           . venv/bin/activate
           python3 sandbox/json_builder.py