version: 2.1

orbs:
  sauce-connect: saucelabs/sauce-connect@1.0.1

workflows:
  browser_tests:
    jobs:
      - sauce-connect/with_proxy:
          steps:
            - run: 
                command: |
                  python3 -m venv venv
                  . venv/bin/activate
                  pip install -r requirements.txt
                  pytest tests/
          version: 4.5.4